options:
  merge-default-rules: false
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - 'public/**/*'
    - 'node_modules/**/*'
rules:
  no-ids: 2
  no-important: 2
  no-vendor-prefixes: 2
  no-url-protocols: 2
  indentation:
    - 2
    - size: 2
  single-line-per-selector: 1
  one-declaration-per-line: 1
  empty-line-between-blocks: 0
  property-sort-order:
    - 1
    - order: smacss
  leading-zero:
    - 2
    - include: true
  brace-style: 1
  space-before-brace: 2
  trailing-semicolon: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  attribute-quotes: 1
  quotes:
    - 2
    - style: single
  no-invalid-hex: 2
